### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/invenio-workflows#5]
Since the move to ElasticSearch 2.0, the size is now restricted to 10000, so the following code breaks https://github.com/inspirehep/invenio-workflows/blob/master/invenio_workflows/search.py#L38-L40

Pagination needs to be implemented in a similar way as in the search API:

```python
response.body.update({
        'size': int(rg),
        'from': jrec-1,
        'aggs': cfg['SEARCH_ELASTIC_AGGREGATIONS'].get(
            collection.name.lower(), {}
        )
    })
```

**Comment by jalavik** [comment]
Closed by 73beda3abb55fe16c7558f675d2c3243751bfb08
